import { COLORS } from "./colors";

export const TOKENS = {
  spacing: {
    xs:    "4px",
    sm:    "8px",
    md:    "12px",
    lg:    "16px",
    xl:    "24px",
    "2xl": "32px",
    "3xl": "48px",
  },
  radius: {
    sm:   "8px",
    md:   "12px",
    lg:   "14px",
    xl:   "18px",
    "2xl":"22px",
    full: "9999px",
  },
  fontSize: {
    title:    "22px",
    subtitle: "14px",
    label:    "13px",
    body:     "14px",
    input:    "14px",
    button:   "15px",
    caption:  "12px",
    micro:    "11px",
    aux:      "12px",
  },
  fontWeight: {
    normal:   "400",
    medium:   "500",
    semibold: "600",
    bold:     "700",
    black:    "900",
  },
  lineHeight: {
    tight:   "1.2",
    normal:  "1.5",
    relaxed: "1.7",
  },
  control: {
    inputHeight:    "46px",
    selectHeight:   "46px",
    btnSecondary:   "48px",
    btnPrimary:     "52px",
    radius:         "14px",
    padding:        "12px",
    gapV:           "8px",
    gapH:           "10px",
  },
  ball: {
    xl:      "64px",
    lg:      "52px",
    md:      "42px",
    sm:      "34px",
    xs:      "28px",
    mdMobile:"36px",
    lgMobile:"44px",
  },
  transition: {
    fast:   "all 0.12s ease",
    normal: "all 0.20s ease",
    slow:   "all 0.35s ease",
  },
  shadow: {
    sm:   "0 2px 8px rgba(0,0,0,0.35)",
    md:   "0 4px 16px rgba(0,0,0,0.45)",
    lg:   "0 8px 32px rgba(0,0,0,0.55)",
    glow: "0 0 20px rgba(0,210,255,0.25)",
  },
  colors: COLORS,
} as const;
